import { MatchingQuestion, MultipleChoiceQuestion, NumericQuestion, OrderingQuestion, Quiz, SingleChoiceQuestion, TextQuestion, TrueFalseQuestion } from "@/lib/types";

const test: Quiz = {
	id: "test",
	name: "Test",
	description: "Ein Quiz, das alle verfügbaren Fragetypen auf dieser Plattform demonstriert.",
	questions: [
		{
			id: "1",
			shortQuestion: "Form der Erde",
			question: "Ist die Erde flach?",
			correctAnswer: false,
		} as TrueFalseQuestion,
		{
			id: "2",
			shortQuestion: "Quadratwurzelberechnung",
			question: "Was ist die Quadratwurzel von 16?",
			correctAnswer: 4,
			tolerance: 0.001,
		} as NumericQuestion,
		{
			id: "3",
			shortQuestion: "Größter Ozean",
			question: "Nennen Sie den größten Ozean der Erde.",
			minLength: 3,
			maxLength: 20,
		} as TextQuestion,
		{
			id: "4",
			shortQuestion: "Hauptstadt von Frankreich",
			question: "Was ist die Hauptstadt von Frankreich?",
			correctAnswerIndex: 0,
			answers: [
				{ id: "1", answer: "Paris" },
				{ id: "2", answer: "Berlin" },
				{ id: "3", answer: "Rom" },
			],
		} as SingleChoiceQuestion,
		{
			id: "5",
			shortQuestion: "Primärfarben",
			question: "Welche dieser Farben sind Primärfarben?",
			answers: [
				{ id: "1", answer: "Rot", isCorrect: true },
				{ id: "2", answer: "Grün", isCorrect: false },
				{ id: "3", answer: "Blau", isCorrect: true },
				{ id: "4", answer: "Gelb", isCorrect: true },
				{ id: "5", answer: "Lila", isCorrect: false },
			],
		} as MultipleChoiceQuestion,
		{
			id: "6",
			shortQuestion: "Planetenreihenfolge",
			question: "Ordnen Sie diese Planeten in der Reihenfolge von der nächsten zur entferntesten von der Sonne.",
			items: [
				{ id: "1", answer: "Erde", correctPosition: 2 },
				{ id: "2", answer: "Merkur", correctPosition: 0 },
				{ id: "3", answer: "Venus", correctPosition: 1 },
				{ id: "4", answer: "Mars", correctPosition: 3 },
			],
		} as OrderingQuestion,
		{
			id: "7",
			shortQuestion: "Länder und Hauptstädte",
			question: "Ordnen Sie diese Länder ihren Hauptstädten zu.",
			items: [
				{ id: "1", answer: "USA" },
				{ id: "2", answer: "Japan" },
				{ id: "3", answer: "Ägypten" },
			],
			matches: [
				{ id: "4", answer: "Washington D.C.", matchesTo: "1" },
				{ id: "5", answer: "Tokio", matchesTo: "2" },
				{ id: "6", answer: "Kairo", matchesTo: "3" },
			],
		} as MatchingQuestion,
	],
};

const basicsInProgrammingVariables: Quiz = {
	id: "bp-variables",
	name: "Grundlagen der Programmierung: Variablen",
	description: "Ein Quiz über Datentypen sowie die Deklaration und Initialisierung von Variablen in Java.",
	questions: [
		{
			id: "v1",
			shortQuestion: "Datentyp ändern",
			question: "Kann eine Variable in Java ihren Datentyp nach der Deklaration ändern?",
			correctAnswer: false,
		} as TrueFalseQuestion,
		{
			id: "v2",
			shortQuestion: "Addition von Variablen",
			question: "Wenn int a = 7; und int b = 3; definiert sind, was ist der Wert von a + b?",
			correctAnswer: 10,
		} as NumericQuestion,
		{
			id: "v3",
			shortQuestion: "Ganzzahl-Datentyp",
			question: "Welcher Datentyp wird für ganze Zahlen verwendet?",
			correctAnswerIndex: 0,
			answers: [
				{ id: "v3a", answer: "int" },
				{ id: "v3b", answer: "double" },
				{ id: "v3c", answer: "char" },
				{ id: "v3d", answer: "boolean" },
			],
		} as SingleChoiceQuestion,
		{
			id: "v4",
			shortQuestion: "Dezimalzahl-Datentyp",
			question: "Welcher Datentyp eignet sich am besten für die Speicherung der Zahl 3.14?",
			correctAnswerIndex: 0,
			answers: [
				{ id: "v4a", answer: "double" },
				{ id: "v4b", answer: "int" },
				{ id: "v4c", answer: "char" },
				{ id: "v4d", answer: "boolean" },
			],
		} as SingleChoiceQuestion,
		{
			id: "v5",
			shortQuestion: "Primitive Datentypen",
			question: "Welche der folgenden sind primitive Datentypen in Java?",
			answers: [
				{ id: "v5a", answer: "int", isCorrect: true },
				{ id: "v5b", answer: "double", isCorrect: true },
				{ id: "v5c", answer: "String", isCorrect: false },
				{ id: "v5d", answer: "boolean", isCorrect: true },
				{ id: "v5e", answer: "char", isCorrect: true },
			],
		} as MultipleChoiceQuestion,
		{
			id: "v6",
			shortQuestion: "Datentypen zuordnen",
			question: "Ordnen Sie die Datentypen den entsprechenden Werten zu:",
			items: [
				{ id: "v6a", answer: "int" },
				{ id: "v6b", answer: "double" },
				{ id: "v6c", answer: "char" },
				{ id: "v6d", answer: "boolean" },
				{ id: "v6e", answer: "String" },
			],
			matches: [
				{ id: "v6f", answer: "42", matchesTo: "v6a" },
				{ id: "v6g", answer: "3.14", matchesTo: "v6b" },
				{ id: "v6h", answer: "'A'", matchesTo: "v6c" },
				{ id: "v6i", answer: "true", matchesTo: "v6d" },
				{ id: "v6j", answer: "\"Hallo Welt\"", matchesTo: "v6e" },
			],
		} as MatchingQuestion,
		{
			id: "v7",
			shortQuestion: "Datentypen zuordnen",
			question: "Ordnen Sie die Datentypen den entsprechenden Werten zu:",
			items: [
				{ id: "v7a", answer: "int" },
				{ id: "v7b", answer: "double" },
				{ id: "v7c", answer: "char" },
				{ id: "v7d", answer: "boolean" },
				{ id: "v7e", answer: "String" },
			],
			matches: [
				{ id: "v7f", answer: "-600", matchesTo: "v7a" },
				{ id: "v7h", answer: "'\\\\'", matchesTo: "v7c" },
				{ id: "v7g", answer: "-.4", matchesTo: "v7b" },
				{ id: "v7i", answer: "false", matchesTo: "v7d" },
				{ id: "v7j", answer: "\"Test\"", matchesTo: "v7e" },
			],
		} as MatchingQuestion,
		{
			id: "v8",
			shortQuestion: "Wertzuweisung zuordnen",
			question: "Ordnen Sie die Variablendeklarationen den korrekten Wertzuweisungen zu:",
			items: [
				{ id: "v8a", answer: "int zahl;" },
				{ id: "v8b", answer: "double wert;" },
				{ id: "v8c", answer: "char buchstabe;" },
				{ id: "v8d", answer: "boolean wahr;" },
				{ id: "v8e", answer: "String text;" },
			],
			matches: [
				{ id: "v8f", answer: "zahl = 100;", matchesTo: "v8a" },
				{ id: "v8g", answer: "wert = 9.99;", matchesTo: "v8b" },
				{ id: "v8h", answer: "buchstabe = 'Z';", matchesTo: "v8c" },
				{ id: "v8i", answer: "wahr = false;", matchesTo: "v8d" },
				{ id: "v8j", answer: "text = \"Java\";", matchesTo: "v8e" },
			],
		} as MatchingQuestion,
		{
			id: "v9",
			shortQuestion: "Syntax-Fehler",
			question: "Welche der folgenden Deklarationen enthält einen Syntax-Fehler?",
			answers: [
				{ id: "v9a", answer: "int i = 45.0;", isCorrect: true },
				{ id: "v9b", answer: "double = 36;", isCorrect: true },
				{ id: "v9c", answer: "String s = 'A';", isCorrect: true },
				{ id: "v9d", answer: "boolean = True;", isCorrect: true },
				{ id: "v9e", answer: "char c = \"X\"", isCorrect: true },
			],
		} as MultipleChoiceQuestion,
		{
			id: "v10",
			shortQuestion: "Deklaration",
			question: "Was stellt folgender Ausdruck dar: DatenTyp Name = Wert;",
			correctAnswerIndex: 1,
			answers: [
				{ id: "v10a", answer: "Dieser Ausdruck ist Synaxfehlerfrei und kann direkt in Java verwendet werden." },
				{ id: "v10b", answer: "Dies ist ein Muster für die Deklaration und Zuweisung einer Variable in Java." },
				{ id: "v10c", answer: "Der Ausdruck hat in der Programmiersprache Java keine Bedeutung." },
			],
		} as SingleChoiceQuestion,
	],
};

const operationsOnVariables: Quiz = {
	id: "bp-operations",
	name: "Grundlagen der Programmierung: Operationen mit Variablen",
	description: "Ein Quiz über arithmetische Operationen (+, -, *, /, %) mit verschiedenen Datentypen in Java.",
	questions: [
		{
			id: "o1",
			shortQuestion: "Integer-Division",
			question: "Wenn int a = 7; und int b = 2; definiert sind, was ist der Wert von a / b?",
			correctAnswer: 3,
		} as NumericQuestion,
		{
			id: "o2",
			shortQuestion: "Double-Division",
			question: "Wenn double a = 7.0; und double b = 2.0; definiert sind, was ist der Wert von a / b?",
			correctAnswer: 3.5,
			tolerance: 0.01,
		} as NumericQuestion,
		{
			id: "o3",
			shortQuestion: "Modulo-Operator",
			question: "Wenn int a = 10; und int b = 3; definiert sind, was ist der Wert von a % b?",
			correctAnswer: 1,
		} as NumericQuestion,
		{
			id: "o4",
			shortQuestion: "String-Konkatenation",
			question: "Ist der Operator + der einzige Operator, der mit String-Variablen verwendet werden kann?",
			correctAnswer: true,
		} as TrueFalseQuestion,
		{
			id: "o5",
			shortQuestion: "Gemischte Typen",
			question: "Wenn int a = 5; und double b = 2.0; definiert sind, was ist der Datentyp des Ergebnisses von a / b?",
			correctAnswerIndex: 0,
			answers: [
				{ id: "o5a", answer: "double" },
				{ id: "o5b", answer: "int" },
				{ id: "o5c", answer: "float" },
				{ id: "o5d", answer: "String" },
			],
		} as SingleChoiceQuestion,
		{
			id: "o6",
			shortQuestion: "String und Integer",
			question: "Was ist das Ergebnis von \"10\" + 5 in Java?",
			correctAnswerIndex: 0,
			answers: [
				{ id: "o6a", answer: "\"105\"" },
				{ id: "o6b", answer: "15" },
				{ id: "o6c", answer: "\"15\"" },
				{ id: "o6d", answer: "Kompilierungsfehler" },
			],
		} as SingleChoiceQuestion,
		{
			id: "o7",
			shortQuestion: "Operatorenreihenfolge",
			question: "Was ist das Ergebnis von 2 + 3 * 4?",
			correctAnswer: 14,
		} as NumericQuestion,
		{
			id: "o8",
			shortQuestion: "Addition von Booleans",
			question: "Wenn boolean a = true; und boolean b = false; definiert sind, was ist das Ergebnis von a + b?",
			correctAnswerIndex: 4,
			answers: [
				{ id: "o8a", answer: "true" },
				{ id: "o8b", answer: "false" },
				{ id: "o8c", answer: "1" },
				{ id: "o8d", answer: "0" },
				{ id: "o8e", answer: "Kompilierungsfehler" },
			],
		} as SingleChoiceQuestion,
		{
			id: "o9",
			shortQuestion: "Gültige Operationen",
			question: "Welche der folgenden Operationen sind in Java erlaubt?",
			answers: [
				{ id: "o9a", answer: "\"Hallo\" + \"Welt\"", isCorrect: true },
				{ id: "o9b", answer: "\"Hallo\" - \"Welt\"", isCorrect: false },
				{ id: "o9c", answer: "5 + 3.14", isCorrect: true },
				{ id: "o9d", answer: "10 % 3", isCorrect: true },
				{ id: "o9e", answer: "\"5\" * 3", isCorrect: false },
			],
		} as MultipleChoiceQuestion,
		{
			id: "o10",
			shortQuestion: "Operatorenpriorität",
			question: "Ordnen Sie die folgenden Operatoren nach ihrer Priorität (von höchster zu niedrigster):",
			items: [
				{ id: "o10a", answer: "* / %", correctPosition: 0 },
				{ id: "o10b", answer: "+ -", correctPosition: 1 },
				{ id: "o10c", answer: "=", correctPosition: 2 },
			],
		} as OrderingQuestion,
		{
			id: "o11",
			shortQuestion: "Rechenoperationen",
			question: "Ordnen Sie die Ganzzahl Operationen ihren Ergebnissen zu:",
			items: [
				{ id: "o11a", answer: "5 + 3" },
				{ id: "o11b", answer: "5 - 3" },
				{ id: "o11c", answer: "5 * 3" },
				{ id: "o11d", answer: "5 / 2" },
				{ id: "o11e", answer: "5 % 2" },
			],
			matches: [
				{ id: "o11f", answer: "8", matchesTo: "o11a" },
				{ id: "o11g", answer: "2", matchesTo: "o11b" },
				{ id: "o11h", answer: "15", matchesTo: "o11c" },
				{ id: "o11i", answer: "2", matchesTo: "o11d" },
				{ id: "o11j", answer: "1", matchesTo: "o11e" },
			],
		} as MatchingQuestion,
		{
			id: "op12",
			shortQuestion: "String-Operationen",
			question: "Was ist das Ergebnis der folgenden Operationen?",
			items: [
				{ id: "o12a", answer: "\"Java\" + \"Script\"" },
				{ id: "o12b", answer: "\"Wert: \" + 42" },
				{ id: "o12c", answer: "\"\" + 7 + 3" },
				{ id: "o12d", answer: "7 + 3 + \"\"" },
			],
			matches: [
				{ id: "o12e", answer: "\"JavaScript\"", matchesTo: "o12a" },
				{ id: "o12f", answer: "\"Wert: 42\"", matchesTo: "o12b" },
				{ id: "o12g", answer: "\"73\"", matchesTo: "o12c" },
				{ id: "o12h", answer: "\"10\"", matchesTo: "o12d" },
			],
		} as MatchingQuestion,
	],
};

const basicsInProgrammingArrays: Quiz = {
	id: "bp-arrays",
	name: "Grundlagen der Programmierung: Arrays",
	description: "Ein Quiz über Arrays und deren Deklaration und Initialisierung in Java.",
	questions: [
		{
			id: "a1",
			shortQuestion: "Unterschiedliche Datentypen",
			question: "Kann ein Java-Array Elemente unterschiedlicher Datentypen enthalten?",
			correctAnswer: false,
		} as TrueFalseQuestion,
		{
			id: "a2",
			shortQuestion: "Array-Indizierung",
			question: "Die Indizierung eines Arrays beginnt bei 1.",
			correctAnswer: false,
		} as TrueFalseQuestion,
		{
			id: "a3",
			shortQuestion: "Array-Größe",
			question: "Wie viele Elemente hat das Array: int[] zahlen = {5, 10, 15, 20, 25};",
			correctAnswer: 5,
		} as NumericQuestion,
		{
			id: "a4",
			shortQuestion: "Letzter Index",
			question: "Wenn ein Array 8 Elemente hat, was ist der Index des letzten Elements?",
			correctAnswer: 7,
		} as NumericQuestion,
		{
			id: "a5",
			shortQuestion: "Array-Deklaration",
			question: "Welche der folgenden Aussagen deklariert ein Array von 10 Kommazahlen in Java?",
			correctAnswerIndex: 0,
			answers: [
				{ id: "a5a", answer: "double[] zahlen = new double[10];" },
				{ id: "a5b", answer: "double zahlen[10];" },
				{ id: "a5c", answer: "double zahlen = new double[10];" },
				{ id: "a5d", answer: "double[10] zahlen;" },
			],
		} as SingleChoiceQuestion,
		{
			id: "a6",
			shortQuestion: "Array-Zugriff",
			question: "Wie greift man auf das erste Element eines Arrays mit Namen 'array' zu?",
			correctAnswerIndex: 0,
			answers: [
				{ id: "a6a", answer: "array[0]" },
				{ id: "a6b", answer: "array[1]" },
				{ id: "a6c", answer: "array(0)" },
				{ id: "a6d", answer: "array.first()" },
			],
		} as SingleChoiceQuestion,
		{
			id: "a7",
			shortQuestion: "Array-Zuweisung",
			question: "Wie weißt man dem zweiten Element eines Arrays mit Namen 'array' den Wert 42 zu?",
			correctAnswerIndex: 2,
			answers: [
				{ id: "a7a", answer: "array[0] = 42;" },
				{ id: "a7b", answer: "array(1) = 42;" },
				{ id: "a7c", answer: "array[1] = 42;" },
				{ id: "a7d", answer: "array.second() = 42;" },
			],
		} as SingleChoiceQuestion,
		{
			id: "a8",
			shortQuestion: "String-Array",
			question: "Wie erstellt man ein Array mit den Wochentagen?",
			correctAnswerIndex: 2,
			answers: [
				{ id: "a8a", answer: "String tage = new String { \"Montag\", \"Dienstag\", \"Mittwoch\" };" },
				{ id: "a8b", answer: "String[3] tage = \"Montag\", \"Dienstag\", \"Mittwoch\";" },
				{ id: "a8c", answer: "String[] tage = new String[] { \"Montag\", \"Dienstag\", \"Mittwoch\" };" },
				{ id: "a8d", answer: "String tage[] = new String[] ( \"Montag\", \"Dienstag\", \"Mittwoch\" );" },
			],
		} as SingleChoiceQuestion,
		{
			id: "a9",
			shortQuestion: "Array-Initialisierung",
			question: "Welche der folgenden sind gültige Wege, ein Array in Java zu initialisieren?",
			answers: [
				{ id: "a9a", answer: "int[] zahlen = new int[5];", isCorrect: true },
				{ id: "a9b", answer: "int[] zahlen = {1, 2, 3, 4, 5};", isCorrect: true },
				{ id: "a9c", answer: "int zahlen[] = new int[5];", isCorrect: true },
				{ id: "a9d", answer: "int[5] zahlen = new int[];", isCorrect: false },
			],
		} as MultipleChoiceQuestion,
		{
			id: "a10",
			shortQuestion: "Array-Typen",
			question: "Welche der folgenden Arrays können in Java erstellt werden?",
			answers: [
				{ id: "a10a", answer: "int[] zahlen", isCorrect: true },
				{ id: "a10b", answer: "double[] werte", isCorrect: true },
				{ id: "a10c", answer: "char[] buchstaben", isCorrect: true },
				{ id: "a10d", answer: "boolean[] wahrheitswerte", isCorrect: true },
				{ id: "a10e", answer: "String[] texte", isCorrect: true },
			],
		} as MultipleChoiceQuestion,
		{
			id: "a11",
			shortQuestion: "Array-Konzepte",
			question: "Ordnen Sie die Array-Konzepte den entsprechenden Beschreibungen zu:",
			items: [
				{ id: "a11a", answer: "array.length" },
				{ id: "a11b", answer: "array[0]" },
				{ id: "a11c", answer: "new double[10]" },
				{ id: "a11d", answer: "double[] array" },
			],
			matches: [
				{ id: "a11e", answer: "Gibt die Anzahl der Elemente zurück", matchesTo: "a11a" },
				{ id: "a11f", answer: "Greift auf das erste Element zu", matchesTo: "a11b" },
				{ id: "a11g", answer: "Erstellt ein Array mit 10 Elementen", matchesTo: "a11c" },
				{ id: "a11h", answer: "Deklariert ein Array", matchesTo: "a11d" },
			],
		} as MatchingQuestion,
		{
			id: "a12",
			shortQuestion: "Arrays verschiedener Typen",
			question: "Ordnen Sie die Array-Deklarationen den korrekten Beispielwerten zu:",
			items: [
				{ id: "a12a", answer: "int[] zahlen = new int[]" },
				{ id: "a12b", answer: "double[] werte = new double[]" },
				{ id: "a12c", answer: "char[] buchstaben = new char[]" },
				{ id: "a12d", answer: "boolean[] flags = new boolean[]" },
				{ id: "a12e", answer: "String[] namen = new String[]" },
			],
			matches: [
				{ id: "a12f", answer: "{1, 2, 3, 4, 5};", matchesTo: "a12a" },
				{ id: "a12g", answer: "{3.14, 2.71, 9.81};", matchesTo: "a12b" },
				{ id: "a12h", answer: "{'J', 'a', 'v', 'a'};", matchesTo: "a12c" },
				{ id: "a12i", answer: "{true, false, true};", matchesTo: "a12d" },
				{ id: "a12j", answer: "{\"Anna\", \"Max\", \"Tom\"};", matchesTo: "a12e" },
			],
		} as MatchingQuestion,
		{
			id: "v13",
			shortQuestion: "Deklaration",
			question: "Was stellt folgender Ausdruck dar: DatenTyp[] ArrayName = Wert[Größe];",
			correctAnswerIndex: 1,
			answers: [
				{ id: "v13a", answer: "Dieser Ausdruck ist Synaxfehlerfrei und kann direkt in Java verwendet werden." },
				{ id: "v13b", answer: "Dies ist ein Muster für die Deklaration eines Arrays mit einer definierten Größe." },
				{ id: "v13c", answer: "Der Ausdruck hat in der Programmiersprache Java keine Bedeutung." },
			],
		} as SingleChoiceQuestion,
	],
};

export const quizzes: Quiz[] = [
	test,
	basicsInProgrammingVariables,
	operationsOnVariables,
	basicsInProgrammingArrays,
];
