services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: quiz-web:latest
    container_name: quiz-web
    restart: unless-stopped
    volumes:
      - ./quizzes:/app/quizzes
    ports:
      - "3006:3000"
