services:
  web:
    image: quiz-web:latest
    container_name: quiz-web
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3006" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    volumes:
      - ./quizzes:/app/quizzes
    ports:
      - "3006:3000"
    restart: unless-stopped
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
